name: Frontend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (legacy mode)
        run: npm install --legacy-peer-deps
        working-directory: .

      - name: Downgrade TypeScript (to avoid conflicts)
        run: npm install typescript@4.9.5 --save-dev
        working-directory: .

      - name: Install testing dependencies
        run: npm install --save-dev @testing-library/react @testing-library/jest-dom @testing-library/dom --legacy-peer-deps
        working-directory: .

      - name: Run tests
        run: npm test
        working-directory: .

      - name: Build the project
        run: CI=false npm run build
        working-directory: .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
