name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Clean environment
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force

      - name: Install dependencies
        run: |
          # 1) Installer en ignorant les conflits pour TS/i18next/CRA
          npm install --legacy-peer-deps

          # 2) Forcer une version d'Ajv & Ajv-keywords compatible (8.x & 5.x)
          npm install ajv@^8.0.0 ajv-keywords@^5.0.0 --save-dev --legacy-peer-deps

      - name: Run tests
        run: npm test

      - name: Build the project
        run: |
          # Désactiver le mode CI pour éviter l'arrêt sur warning
          CI=false npm run build


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
